#cloud-config
packages:
  - nodejs 
  - npm

runcmd:
  - npm install -g n
  - n latest
  - apt-get install -y git 
  - |
  git_clone_retry() { 
    local retries=0
    local max_retries=3 
    local interval=20
    until git clone https://github.com/manuelenrq9/CRUDubuntu.git backend || [ $retries -eq $max_retries ]; do
    retries=$((retries+1))
    sleep $interval 
    done
  }
git_clone_retry EOF